### PR TITLE
Added premailer to inline all css rules

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
Depends on https://github.com/drone/drone-go/pull/19

**Comment by tboerger** [comment]
After merging the bugfix for drone-go we should even get on gmail nice looking HTML mails as you can see below.

screenshot from 2016-02-02 11-46-27

**Comment by bradrydzewski** [comment]
LGTM

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
